version: '1'

services:
  app:
    build: .
    container_name: todo-app
    env_file: .env
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db 
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:

      