### GET /
GET http://localhost:5000

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"aaa",
    "password":"aaaaa"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"aaa",
    "password":"aaaaa"
}